# Site settings

title: Milestone
# email: mauro@topics.it

description: > # this means to ignore newlines until "baseurl:"
  The journey is the most important thing, not the destination.
  Find your next destination and start travelling again.

excerpt_separator: <!--more-->
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://milestone.topics.it" # the base hostname & protocol for your site

twitter_username: mauroservienti
github_username:  topics
github_repository:  milestone.github.io

highlighter: rouge

markdown: kramdown

exclude: ['README.md', 'LICENSE']

encoding: utf-8

collections:
  events:
    output: true
  talks:
    output: true
