# Site settings

title: Milestone

description: > # this means to ignore newlines until "baseurl:"
  The journey is the most important thing, not the destination.
  Find your next destination and start travelling again.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://milestone.topics.it" # the base hostname & protocol for your site
excerpt_separator: <!--more-->

twitter_username: mauroservienti
github_username:  topics
github_repository:  milestone.github.io

highlighter: rouge
markdown: kramdown
exclude: ['README.md', 'LICENSE', 'CNAME']
encoding: utf-8
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

collections:
  events:
    output: true
  talks:
    output: true
  tags:
    output: true
